In [2]:
# Creating an array
import numpy as np
np.zeros((4,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [3]:
np.ones((5,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.empty((2,6))

array([[0.00000000e+000, 0.00000000e+000, 2.96439388e-323,
        0.00000000e+000, 1.48539705e-313, 5.74084271e+169],
       [5.58171564e-091, 9.76835929e+165, 1.52410723e-052,
        3.92588485e-033, 3.99910963e+252, 8.34403735e-309]])

In [8]:
# Reshape an array

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(a.shape)

(10,)


In [12]:
b = a.reshape(2,5)

# Reshape function creates a new object

b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr = np.arange(25, 55).reshape(5,6)
arr

# While reshaping an array no of element in an array and product of rows and column while reshaoing should be same

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [18]:
# Reshaping using shape attribute

arr.shape = 2, 5, 3
arr

# Makes the changes to existing array object

array([[[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]],

       [[40, 41, 42],
        [43, 44, 45],
        [46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [24]:
# Reshaping 2D or 3D matrix to 1D Matrix
arr1 = arr.ravel()
arr1

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [29]:
# arr1.reshape(2, -1, -1)

# any one dimension, either, row, or coloumn or rank can be -negative

ValueError: can only specify one unknown dimension

In [38]:
# Transpose - Row converted to column and column converted to row

# print(arr)
# print()
# print(arr.T)

# print(arr)
# arr.T


In [39]:
# Basic Operations on an array
# Arithmetic, Compariosn, Equality, 

arr1 = np.array([10,20,30,40,50])
arr2 = np.array([11,22,33,44,55])
arr1

array([10, 20, 30, 40, 50])

In [40]:
arr2

array([11, 22, 33, 44, 55])

In [41]:
arr1 + arr2

array([ 21,  42,  63,  84, 105])

In [45]:
arr1 + 2

array([12, 22, 32, 42, 52])

In [42]:
arr1 * 2

array([ 20,  40,  60,  80, 100])

In [43]:
arr1 / 2

array([ 5., 10., 15., 20., 25.])

In [44]:
arr1 % 2

array([0, 0, 0, 0, 0])

In [46]:
arr1 > 30

array([False, False, False,  True,  True])

In [52]:
# Multiplication on an array
    # Scalar Mulltiplication
    # Vector Multiplication - dot product

    
# Scalar product
print(arr1 * 3)    
# print(arr1 * arr2)   # Shape of both the array should be same


# Vector product - np.dot(arr1, arr2)
# np.dot(arr1, arr2)

# Vector product on 2D matrix
# no of columns in first matrix and no of rows in 2nd matrix should be same
# Resultant matrix shape will be = (no of rows in first matrix, no of column in 2nd matrix)


[[ 75  78  81  84  87  90]
 [ 93  96  99 102 105 108]
 [111 114 117 120 123 126]
 [129 132 135 138 141 144]
 [147 150 153 156 159 162]]


ValueError: operands could not be broadcast together with shapes (5,6) (5,) 

In [65]:
arr1 = np.arange(25, 55).reshape(5, 6)
arr2 = np.arange(1, 37).reshape(6, 6)
np.dot(arr1, arr2)

array([[2745, 2910, 3075, 3240, 3405, 3570],
       [3321, 3522, 3723, 3924, 4125, 4326],
       [3897, 4134, 4371, 4608, 4845, 5082],
       [4473, 4746, 5019, 5292, 5565, 5838],
       [5049, 5358, 5667, 5976, 6285, 6594]])

In [63]:
# Compound assignment operation
arr1 &= 2
arr1

array([[0, 2, 2, 0, 0, 2],
       [2, 0, 0, 2, 2, 0],
       [0, 2, 2, 0, 0, 2],
       [2, 0, 0, 2, 2, 0],
       [0, 2, 2, 0, 0, 2]])

In [67]:
# unary operations - sum(), max, min
arr1.sum()

1185

In [69]:
arr1

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [68]:
# Finding sum of array elements in each row
arr1.sum(axis = 0)

array([185, 190, 195, 200, 205, 210])

In [70]:
# Finding sum of array elements in each column
arr1.sum(axis = 1)

array([165, 201, 237, 273, 309])

In [71]:
# Finding maximum value from an array
arr.max()

54

In [72]:
# Finding max element of array elements in each row
arr1.max(axis = 0)

array([49, 50, 51, 52, 53, 54])

In [73]:
# Finding max element of array elements in each col
arr1.max(axis = 1)

array([30, 36, 42, 48, 54])

In [75]:
# arr1 and 2

# &, |

# Indexing and slicing


In [76]:
arr1 = np.arange(25, 35)
arr1

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [77]:
arr1[0]

25

In [78]:
arr1[-1]

34

In [82]:
arr1[2:6:2]

arr1[::-1]

array([34, 33, 32, 31, 30, 29, 28, 27, 26, 25])

In [83]:
# on 2D array
arr2 = np.arange(25, 61).reshape(6, 6)
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [85]:
# While performing indexing or slicing on an array, then first element should be row and second should be column
arr2[0]
arr2[-1]


array([55, 56, 57, 58, 59, 60])

In [89]:
arr2[::, 0]

array([25, 31, 37, 43, 49, 55])

In [91]:
# To access a particular element
arr2[2, 2]
arr2[2][2]

39

In [98]:
# arr3 = arr2.reshape(3, 3, 4)
# arr3[1][1][1]
# arr3[1,1,1]

In [99]:
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [109]:
# [[31, 33, 35],
# [43, 45, 47]]


arr2[1:4:2, ::2]



# arr2[3:, 3:]

array([[31, 33, 35],
       [43, 45, 47]])

In [104]:
arr2[3:6,3:6]

array([[46, 47, 48],
       [52, 53, 54],
       [58, 59, 60]])

In [107]:
arr2

# [33, 38, 45, 40]

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [110]:
row_index = [1, 2, 3, 2]
col_index = [2, 1, 2, 3]
arr2[row_index, col_index]

array([33, 38, 45, 40])

In [111]:
fruit = np.array([["Banana","Mango","Guava","Avacado"],
            ["Papaya","Jack fruit","Plum","Strawberry"],
            ["Apricot","Apple","Blue berry","Black berry"]])
fruit

array([['Banana', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue berry', 'Black berry']], dtype='<U11')

In [113]:
row_ind = [0, 1, 1, 2]
col_ind = [0, 1, 3, 2]
fruit[row_ind, col_ind] = 'Potato'

In [114]:
fruit

array([['Potato', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Potato', 'Plum', 'Potato'],
       ['Apricot', 'Apple', 'Potato', 'Black berry']], dtype='<U11')

In [149]:
arr3 = np.random.randn(5,6)
arr4 = (arr3 * 100)//1
arr4


array([[ 236.,  157., -159.,  -52.,  -32.,   44.],
       [ -38.,   63.,   38.,  -93.,    5.,   14.],
       [ -15.,  -99.,  -39.,  267.,   11.,  -20.],
       [ -53.,  -91.,   42.,   38.,    7.,  105.],
       [ -16., -130.,  -28.,   -9.,  -10.,  -74.]])

In [129]:
arr4[arr4 > 0]

array([ 36., 151.,  98.,  25.,  50.,  48., 103., 134.,   3., 122., 128.,
       181.,  62.])

In [157]:
arr3 = np.random.randn(5,6)
arr3

-3, +3

array([[ 0.74244639,  0.7212694 ,  0.42763974,  1.1791854 ,  0.03190388,
         0.18075453],
       [ 1.11341921, -1.03922691,  1.26116362,  1.53648136, -0.66109784,
         0.26851711],
       [ 1.41328196, -0.3167652 , -2.01328068, -0.70590105, -0.17789809,
        -0.60355523],
       [-0.43354864, -0.59179865,  1.71249811, -0.75459013,  0.71804592,
         0.78268202],
       [-1.18957189, -1.06297227,  1.36308803, -0.72694508, -0.62055751,
        -0.12313351]])