In [5]:
# Array is collection of homogeneous elements
lst = [10,20.30,30+40j,'Python']
lst

import numpy as np
arr = np.array([10,10.20, 10+20j, 100])
arr

array([ 10.  +0.j,  10.2 +0.j,  10. +20.j, 100.  +0.j])

In [7]:
# Storage of array is efficient
# Doing operation on array is more easier than list.

# Multiplying every element of a list by 2
[i*2 for i in lst]

[20, 40.6, (60+80j), 'PythonPython']

In [8]:
arr * 2

array([ 20.  +0.j,  20.4 +0.j,  20. +40.j, 200.  +0.j])

In [9]:
# Create an array using numpy
import numpy as np

In [34]:
# Create a 1D array using list
arr = np.array([[10],[40,50]])
print(arr)

# Data type of arr
print(type(arr))

[list([10]) list([40, 50])]
<class 'numpy.ndarray'>


<ipython-input-34-0c34c9170a22>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[10],[40,50]])


In [35]:
# Check the type of each element in an array
print(arr.dtype)

# Check the shape of an array
print(arr.shape)

# Check the size of an array
print(arr.size)

object
(2,)
2


In [33]:
# Create a 2D array using tuple
arr = np.array(((10,20,30),(40,50,60), (70,80,90)), dtype = 'int8')
print(arr)

# Data type of arr
print(type(arr))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>


In [24]:
# Check the type of each element in an array
print(arr.dtype)

# Check the shape of an array
print(arr.shape)

# Check the size of an array
print(arr.size)

int8
(3, 3)
9


In [25]:
# Numpy - C
Boolean
int8
in16
int32
int64
float32
float64
complex128
complex256
u8
u16
u32
object

In [28]:
# Create a 1D array using dictionary
arr = np.array({1:190, 2:200, 3:300})
print(arr)

# Data type of arr
print(type(arr))

arr

{1: 190, 2: 200, 3: 300}
<class 'numpy.ndarray'>


array({1: 190, 2: 200, 3: 300}, dtype=object)

In [27]:
# Check the type of each element in an array
print(arr.dtype)

# Check the shape of an array
print(arr.shape)

# Check the size of an array
print(arr.size)

object
()
1


In [29]:
arr = np.array(10)
arr

array(10)

In [31]:
arr.shape
arr.size

1

In [39]:
# Create an array using arange
# Syantax - arange(start, stop, step)
# Step value can be a fraction

arr = np.arange(11, 21, 1)
arr

arr = np.arange(11, 21, 2)
arr

arr = np.arange(20, 10, -1)
arr

arr = np.arange(20, 10, -1.5)
arr

array([20. , 18.5, 17. , 15.5, 14. , 12.5, 11. ])

In [44]:
# Create an array using linspace
# Syntax - linspace(start, stop, no of values)
# Stop value is inclusive

arr = np.linspace(11, 20, 10, dtype = int)
arr

# arr = np.linspace(11, 20, 100)
# arr

# arr = np.linspace(11, 20, 1000)
# arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])